

services:
  web:
    build: .
    image: blood_journal_web
    container_name: blood_journal_web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: blood_journal_db
    restart: always
    environment:
      POSTGRES_USER: blooduser
      POSTGRES_PASSWORD: bloodpass
      POSTGRES_DB: bloodjournal
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
