"""Add tag field to GlucoseEntry

Revision ID: 554f76e15145
Revises: eb2e492869c0
Create Date: 2025-06-03 18:48:41.972127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554f76e15145'
down_revision = 'eb2e492869c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('glucose_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('glucose_entry', schema=None) as batch_op:
        batch_op.drop_column('tag')

    # ### end Alembic commands ###
